-- Migration: Initial schema for DriveEase
-- Run this in your Supabase SQL Editor

-- 1. Cars table
create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  price integer not null,
  seats integer not null default 5,
  fuel text not null,
  badge text not null,
  gradient text not null default 'from-blue-500/20 to-blue-600/10',
  color text not null default '#3b82f6',
  image text not null,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Reservations table
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  car_slug text not null references public.cars(slug) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3. Add contact fields to reservations
alter table public.reservations
  add column if not exists email text,
  add column if not exists phone text not null default '';

-- Add missing fields to cars
alter table public.cars
  add column if not exists transmission text not null default 'Automatique',
  add column if not exists description text default '';

-- 4. Enable RLS
alter table public.cars enable row level security;
alter table public.reservations enable row level security;

-- 5. RLS policies for cars
drop policy if exists "Cars are public readable" on public.cars;
create policy "Cars are public readable"
  on public.cars for select
  using (true);

drop policy if exists "Cars are insertable by authenticated users" on public.cars;
create policy "Cars are insertable by authenticated users"
  on public.cars for insert
  to authenticated
  with check (true);

drop policy if exists "Cars are updatable by authenticated users" on public.cars;
create policy "Cars are updatable by authenticated users"
  on public.cars for update
  to authenticated
  using (true);

drop policy if exists "Cars are deletable by authenticated users" on public.cars;
create policy "Cars are deletable by authenticated users"
  on public.cars for delete
  to authenticated
  using (true);

-- 6. RLS policies for reservations
drop policy if exists "Users can view their own reservations" on public.reservations;
create policy "Users can view their own reservations"
  on public.reservations for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can create reservations" on public.reservations;
create policy "Users can create reservations"
  on public.reservations for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Anyone can create reservations" on public.reservations;
create policy "Anyone can create reservations"
  on public.reservations for insert
  to anon
  with check (user_id is null);

drop policy if exists "Users can update their own reservations" on public.reservations;
create policy "Users can update their own reservations"
  on public.reservations for update
  to authenticated
  using (auth.uid() = user_id);

-- 7. Seed data (optional)
insert into public.cars (slug, name, price, seats, fuel, badge, gradient, color, image, images) values
  ('tesla-model-3', 'Tesla Model 3', 89, 5, 'Électrique', 'Populaire', 'from-blue-500/20 to-blue-600/10', '#3b82f6',
   'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=85',
   '["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=85","https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=600&q=85","https://images.unsplash.com/photo-1536700503339-0e4f1b8e9f3a?w=600&q=85"]'::jsonb),
  ('bmw-serie-3', 'BMW Série 3', 75, 5, 'Essence', 'Premium', 'from-indigo-500/20 to-indigo-600/10', '#6366f1',
   'https://images.unsplash.com/photo-1556189250-72a3a32b1e3e?w=600&q=85',
   '["https://images.unsplash.com/photo-1556189250-72a3a32b1e3e?w=600&q=85","https://images.unsplash.com/photo-1523983388277-336a66bf9bcd?w=600&q=85","https://images.unsplash.com/photo-1583267746897-2cf415887172?w=600&q=85"]'::jsonb),
  ('mercedes-classe-c', 'Mercedes Classe C', 82, 5, 'Diesel', 'Premium', 'from-violet-500/20 to-violet-600/10', '#8b5cf6',
   'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=85',
   '["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=85","https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=600&q=85","https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&q=85"]'::jsonb),
  ('audi-q5', 'Audi Q5', 95, 5, 'Hybride', 'SUV', 'from-emerald-500/20 to-emerald-600/10', '#10b981',
   'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=85',
   '["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=85","https://images.unsplash.com/photo-1603584173870-7f23fd4c0a67?w=600&q=85","https://images.unsplash.com/photo-1609521263047-f8f205293f64?w=600&q=85"]'::jsonb),
  ('volkswagen-golf', 'Volkswagen Golf', 45, 5, 'Essence', 'Économique', 'from-amber-500/20 to-amber-600/10', '#f59e0b',
   'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=85',
   '["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=85","https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&q=85","https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=85"]'::jsonb),
  ('porsche-911', 'Porsche 911', 220, 2, 'Essence', 'Sport', 'from-rose-500/20 to-rose-600/10', '#f43f5e',
   'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=600&q=85',
   '["https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=600&q=85","https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=85","https://images.unsplash.com/photo-1619682817481-e994891cd75b?w=600&q=85"]'::jsonb)
on conflict (slug) do nothing;
